### PR TITLE
Fixed Expo compatibility

### PR DESCRIPTION
**Pull request by geeknat**
Uses Native WebView to work in both Expo and Create-react-app apps.

### CODE REVIEW

**Comment by hungdev** [comment]
<WebView/> is going to be removed from the React Native core. So I decided to use react-native-webview as react native team suggests.
https://facebook.github.io/react-native/docs/webview
Note: Expo support for React Native WebView started with Expo SDK v33.0.0.
[Read more](https://github.com/react-native-community/react-native-webview#platforms-supported)

**Comment by geeknat** [comment]
I didn't know it's going to be removed, just read that. I'm using Expo SDK 34.0.0 and I don't know why it crashed on my device, iPhone 7.

**Comment by hungdev** [comment]
Sorry i cant help you because i don't use expo.

**Comment by caelinsutch** [comment]
@hungdev Is this supported by Expo then if React NativeWebView is supported?

**Comment by hungdev** [comment]
@caelinsutch yes, it supported expo when you install the latest version of react native webview

**Pull request closed without merging**
